// 内置板块数据
import type { Sector } from './types'

export const DEFAULT_SECTORS: Sector[] = [
  {
    id: 'ai-chain',
    name: 'AI 产业链',
    description: '人工智能全产业链：芯片/算力、模型/平台、应用/终端、基础设施',
    icon: '🤖',
    isBuiltIn: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    stocks: [
      // 美股 - 算力/芯片
      { symbol: 'NVDA.US', name: 'NVIDIA', market: '美股', layer: '上游·算力', reason: 'AI GPU 龙头', tags: ['核心', '算力'] },
      { symbol: 'AVGO.US', name: 'Broadcom', market: '美股', layer: '上游·算力', reason: '网络芯片 + 定制 ASIC', tags: ['核心'] },
      { symbol: 'AMD.US', name: 'AMD', market: '美股', layer: '上游·算力', reason: 'GPU + CPU 竞争者', tags: ['算力'] },
      { symbol: 'TSM.US', name: 'TSMC', market: '美股', layer: '上游·算力', reason: '先进制程代工', tags: ['核心', '制造'] },
      { symbol: 'MRVL.US', name: 'Marvell', market: '美股', layer: '上游·算力', reason: '定制芯片 + 网络', tags: ['算力'] },
      { symbol: 'QCOM.US', name: 'Qualcomm', market: '美股', layer: '上游·算力', reason: '移动端 AI 芯片', tags: ['端侧'] },
      { symbol: 'INTC.US', name: 'Intel', market: '美股', layer: '上游·算力', reason: 'CPU + Gaudi AI 加速器', tags: ['算力'] },
      // 美股 - 模型/平台
      { symbol: 'MSFT.US', name: 'Microsoft', market: '美股', layer: '中游·模型', reason: 'OpenAI 合作 + Azure AI', tags: ['核心', '云'] },
      { symbol: 'GOOGL.US', name: 'Alphabet', market: '美股', layer: '中游·模型', reason: 'Gemini + TPU + GCP', tags: ['核心', '云'] },
      { symbol: 'META.US', name: 'Meta', market: '美股', layer: '中游·模型', reason: 'Llama 开源模型', tags: ['模型'] },
      { symbol: 'AMZN.US', name: 'Amazon', market: '美股', layer: '中游·模型', reason: 'AWS + Bedrock AI 平台', tags: ['云'] },
      { symbol: 'ORCL.US', name: 'Oracle', market: '美股', layer: '中游·模型', reason: 'AI 云基础设施', tags: ['云'] },
      // 美股 - 应用
      { symbol: 'CRM.US', name: 'Salesforce', market: '美股', layer: '下游·应用', reason: 'AI CRM Agent', tags: ['应用'] },
      { symbol: 'ADBE.US', name: 'Adobe', market: '美股', layer: '下游·应用', reason: '创意 AI 工具', tags: ['应用'] },
      { symbol: 'NOW.US', name: 'ServiceNow', market: '美股', layer: '下游·应用', reason: '企业 AI 自动化', tags: ['应用'] },
      { symbol: 'PLTR.US', name: 'Palantir', market: '美股', layer: '下游·应用', reason: 'AI 数据分析平台', tags: ['应用'] },
      // 美股 - 基础设施
      { symbol: 'VST.US', name: 'Vistra', market: '美股', layer: '基础设施·电力', reason: 'AI 数据中心电力', tags: ['电力'] },
      { symbol: 'CEG.US', name: 'Constellation Energy', market: '美股', layer: '基础设施·电力', reason: '核电供数据中心', tags: ['电力'] },
      { symbol: 'EQIX.US', name: 'Equinix', market: '美股', layer: '基础设施·IDC', reason: '全球数据中心龙头', tags: ['IDC'] },
      { symbol: 'VRT.US', name: 'Vertiv', market: '美股', layer: '基础设施·散热', reason: '数据中心散热方案', tags: ['散热'] },
      // 美股 - 光通信/CPO
      { symbol: 'COHR.US', name: 'Coherent', market: '美股', layer: '上游·光通信', reason: '光模块龙头', tags: ['光模块'] },
      { symbol: 'LITE.US', name: 'Lumentum', market: '美股', layer: '上游·光通信', reason: '光器件', tags: ['光模块'] },
      { symbol: 'ANET.US', name: 'Arista Networks', market: '美股', layer: '中游·网络', reason: 'AI 网络交换机', tags: ['网络'] },
      // 港股
      { symbol: '00700.HK', name: '腾讯控股', market: '港股', layer: '中游·模型', reason: '混元大模型 + AI 应用', tags: ['核心', '模型'] },
      { symbol: '09988.HK', name: '阿里巴巴', market: '港股', layer: '中游·模型', reason: '通义千问 + 阿里云', tags: ['核心', '云'] },
      { symbol: '09888.HK', name: '百度集团', market: '港股', layer: '中游·模型', reason: '文心一言 + 自动驾驶', tags: ['模型'] },
      { symbol: '03690.HK', name: '美团', market: '港股', layer: '下游·应用', reason: 'AI 本地生活', tags: ['应用'] },
      { symbol: '09618.HK', name: '京东集团', market: '港股', layer: '下游·应用', reason: 'AI 供应链 + 物流', tags: ['应用'] },
      { symbol: '01810.HK', name: '小米集团', market: '港股', layer: '下游·终端', reason: 'AI 手机 + IoT', tags: ['终端'] },
      { symbol: '00285.HK', name: '比亚迪电子', market: '港股', layer: '下游·终端', reason: 'AI 硬件代工', tags: ['终端'] },
      { symbol: '02382.HK', name: '舜宇光学', market: '港股', layer: '上游·光学', reason: 'AI 视觉传感器', tags: ['光学'] },
      // A 股 - 算力
      { symbol: '600176.SH', name: '中国巨石', market: 'A股', layer: '上游·材料', reason: 'AI 基建材料', tags: ['材料'] },
      { symbol: '300308.SZ', name: '中际旭创', market: 'A股', layer: '上游·光通信', reason: '800G 光模块龙头', tags: ['核心', '光模块'] },
      { symbol: '002475.SZ', name: '立讯精密', market: 'A股', layer: '上游·连接器', reason: 'AI 服务器连接器', tags: ['连接器'] },
      { symbol: '603019.SH', name: '中科曙光', market: 'A股', layer: '中游·算力', reason: 'AI 服务器 + 超算', tags: ['算力'] },
      { symbol: '002230.SZ', name: '科大讯飞', market: 'A股', layer: '中游·模型', reason: '星火大模型', tags: ['模型'] },
      { symbol: '688256.SH', name: '寒武纪', market: 'A股', layer: '上游·芯片', reason: 'AI 芯片设计', tags: ['芯片'] },
      // 台股
      { symbol: '2330.TW', name: '台积电', market: '美股', layer: '上游·制造', reason: '先进制程垄断', tags: ['核心', '制造'] },
      { symbol: '2308.TW', name: '台达电', market: '美股', layer: '基础设施·电源', reason: 'AI 服务器电源', tags: ['电源'] },
    ]
  },
  {
    id: 'semiconductor',
    name: '半导体',
    description: '半导体产业链：设计、制造、封测、设备、材料',
    icon: '🔬',
    isBuiltIn: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    stocks: [
      { symbol: 'NVDA.US', name: 'NVIDIA', market: '美股', layer: '设计', tags: ['GPU'] },
      { symbol: 'TSM.US', name: 'TSMC', market: '美股', layer: '制造', tags: ['代工'] },
      { symbol: 'AVGO.US', name: 'Broadcom', market: '美股', layer: '设计', tags: ['ASIC'] },
      { symbol: 'AMD.US', name: 'AMD', market: '美股', layer: '设计', tags: ['CPU', 'GPU'] },
      { symbol: 'QCOM.US', name: 'Qualcomm', market: '美股', layer: '设计', tags: ['移动'] },
      { symbol: 'INTC.US', name: 'Intel', market: '美股', layer: '设计+制造', tags: ['IDM'] },
      { symbol: 'MU.US', name: 'Micron', market: '美股', layer: '存储', tags: ['HBM'] },
      { symbol: 'ASML.US', name: 'ASML', market: '美股', layer: '设备', tags: ['光刻机'] },
      { symbol: 'LRCX.US', name: 'Lam Research', market: '美股', layer: '设备', tags: ['刻蚀'] },
      { symbol: 'AMAT.US', name: 'Applied Materials', market: '美股', layer: '设备', tags: ['沉积'] },
      { symbol: 'KLAC.US', name: 'KLA', market: '美股', layer: '设备', tags: ['检测'] },
      { symbol: 'ON.US', name: 'ON Semi', market: '美股', layer: '设计', tags: ['功率'] },
      { symbol: 'TXN.US', name: 'Texas Instruments', market: '美股', layer: '设计', tags: ['模拟'] },
      { symbol: '688256.SH', name: '寒武纪', market: 'A股', layer: '设计', tags: ['AI芯片'] },
      { symbol: '002049.SZ', name: '紫光国微', market: 'A股', layer: '设计', tags: ['安全芯片'] },
      { symbol: '603501.SH', name: '韦尔股份', market: 'A股', layer: '设计', tags: ['CIS'] },
      { symbol: '688981.SH', name: '中芯国际', market: 'A股', layer: '制造', tags: ['代工'] },
      { symbol: '002371.SZ', name: '北方华创', market: 'A股', layer: '设备', tags: ['刻蚀'] },
      { symbol: '688012.SH', name: '中微公司', market: 'A股', layer: '设备', tags: ['刻蚀'] },
      { symbol: '002352.SZ', name: '顺丰控股', market: 'A股', layer: '材料', tags: ['封装材料'] },
    ]
  },
  {
    id: 'new-energy',
    name: '新能源',
    description: '新能源产业链：光伏、风电、储能、新能源车',
    icon: '⚡',
    isBuiltIn: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    stocks: [
      { symbol: 'TSLA.US', name: 'Tesla', market: '美股', layer: '新能源车', tags: ['EV'] },
      { symbol: 'NIO.US', name: 'NIO', market: '美股', layer: '新能源车', tags: ['EV'] },
      { symbol: 'XPEV.US', name: 'XPeng', market: '美股', layer: '新能源车', tags: ['EV'] },
      { symbol: 'LI.US', name: 'Li Auto', market: '美股', layer: '新能源车', tags: ['EV'] },
      { symbol: 'ENPH.US', name: 'Enphase', market: '美股', layer: '光伏', tags: ['逆变器'] },
      { symbol: 'FSLR.US', name: 'First Solar', market: '美股', layer: '光伏', tags: ['组件'] },
      { symbol: 'NEE.US', name: 'NextEra Energy', market: '美股', layer: '风电', tags: ['运营商'] },
      { symbol: '01211.HK', name: '比亚迪', market: '港股', layer: '新能源车', tags: ['核心', 'EV'] },
      { symbol: '09868.HK', name: '小鹏汽车', market: '港股', layer: '新能源车', tags: ['EV'] },
      { symbol: '02015.HK', name: '理想汽车', market: '港股', layer: '新能源车', tags: ['EV'] },
      { symbol: '300750.SZ', name: '宁德时代', market: 'A股', layer: '电池', tags: ['核心'] },
      { symbol: '002594.SZ', name: '比亚迪', market: 'A股', layer: '新能源车', tags: ['核心'] },
      { symbol: '601012.SH', name: '隆基绿能', market: 'A股', layer: '光伏', tags: ['组件'] },
      { symbol: '300274.SZ', name: '阳光电源', market: 'A股', layer: '储能', tags: ['逆变器'] },
      { symbol: '002459.SZ', name: '晶澳科技', market: 'A股', layer: '光伏', tags: ['组件'] },
    ]
  },
  {
    id: 'biotech',
    name: '生物科技',
    description: '创新药、CXO、医疗器械、基因治疗',
    icon: '🧬',
    isBuiltIn: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    stocks: [
      { symbol: 'LLY.US', name: 'Eli Lilly', market: '美股', layer: '创新药', tags: ['GLP-1'] },
      { symbol: 'NVO.US', name: 'Novo Nordisk', market: '美股', layer: '创新药', tags: ['GLP-1'] },
      { symbol: 'ABBV.US', name: 'AbbVie', market: '美股', layer: '创新药', tags: ['免疫'] },
      { symbol: 'AMGN.US', name: 'Amgen', market: '美股', layer: '创新药', tags: ['生物药'] },
      { symbol: 'ISRG.US', name: 'Intuitive Surgical', market: '美股', layer: '医疗器械', tags: ['手术机器人'] },
      { symbol: 'TMO.US', name: 'Thermo Fisher', market: '美股', layer: 'CXO', tags: ['生命科学'] },
      { symbol: 'CRSP.US', name: 'CRISPR Therapeutics', market: '美股', layer: '基因治疗', tags: ['CRISPR'] },
      { symbol: '02269.HK', name: '药明生物', market: '港股', layer: 'CXO', tags: ['核心'] },
      { symbol: '01177.HK', name: '中国生物制药', market: '港股', layer: '创新药', tags: ['仿创'] },
      { symbol: '02359.HK', name: '药明康德', market: '港股', layer: 'CXO', tags: ['核心'] },
      { symbol: '300760.SZ', name: '迈瑞医疗', market: 'A股', layer: '医疗器械', tags: ['核心'] },
      { symbol: '300347.SZ', name: '泰格医药', market: 'A股', layer: 'CXO', tags: ['临床'] },
    ]
  }
]
